@startuml
!theme toy

package Runic <<rectangle>> {
  package Core <<folder>> {
    class Main <<Artifact>> {
      {static} {abstract} CreateApplication(): unique_ptr<Application>
    }

    hide <<Artifact>> circle
    hide <<Artifact>> fields

    struct AppData {
      + name: string
      + version: string
      + identifier: string
    }

    hide AppData methods

    class Application {
      - data: AppData
      - window: unique_ptr<Window>
      + Application(const AppData&, const WindowData&)
    }

    Main *-- Application
    (Main, Application) .. AppData

    struct WindowData {
      + title: string
      + width: uint32
      + height: uint32
    }

    hide WindowData methods

    class Window {
      - data: WindowData
      - native: SDL_window*
      + Window(WindowData)
      + getData(): const WindowData&
      + show(): void
      + hide(): void
    }

    Application *-- Window
    (Application, Window) .. WindowData

    class SDLException {
      + SDLException(const string&)
    }

    hide SDLException fields

    class Log {
      {static} - CoreLogger: shared_ptr<spdlog::logger>
      {static} - ClientLogger: shared_ptr<spdlog::logger>
      {static} + Init(): void
      {static} + GetCore(): shared_ptr<spdlog::logger>&
      {static} + GetClient(): shared_ptr<spdlog::logger>&
    }

    Main --> Log : uses
  }
}

@enduml
