@startuml
!theme toy

package Runic <<rectangle>> {
  package Core <<folder>> {
    class Main <<Artifact>> {
      {static} {abstract} CreateApplication(): unique_ptr<Application>
    }

    hide <<Artifact>> circle
    hide <<Artifact>> fields

    struct AppData {
      + name: string
      + version: string
      + identifier: string
    }

    class Application {
      - data: AppData
      - window: unique_ptr<Window>
      - userDispatch: EventDispatcher
      - systemDispatch: eventDispatcher
      - done: bool
      + Application(const AppData&, const WindowData&)
      + onUpdate(): void
      + isDone(): bool
      + addEventHandler<T>(bool(const T&)): void
      + handleEvent<T>(const T&): void
      - addSystemEventHandler<T>(bool(const T&)): void
      - handleSystemEvent<T>(const T&): void
    }

    Main *-- Application
    (Main, Application) . AppData

    struct WindowData {
      + title: string
      + width: uint32
      + height: uint32
    }

    class Window {
      - data: WindowData
      - native: SDL_window*
      + Window(WindowData)
      + getData(): const WindowData&
      + show(): void
      + hide(): void
    }

    Application *-- Window
    (Application, Window) . WindowData

    class SDLException {
      + SDLException(const string&)
    }

    class Log {
      {static} - CoreLogger: shared_ptr<spdlog::logger>
      {static} - ClientLogger: shared_ptr<spdlog::logger>
      {static} + Init(): void
      {static} + GetCore(): shared_ptr<spdlog::logger>&
      {static} + GetClient(): shared_ptr<spdlog::logger>&
    }

    Main --> Log : initializes

    class Input {
      {static} + IsKeyPressed(Key): bool
      {static} + IsMouseButtonPressed(MouseButton): bool
    }

    package Input as InputPkg {
      enum Key {
        A
        B
        C
        ...
      }

      enum MouseButton {
        Left
        Middle
        Right
        X1
        X2
      }
    }

    Input --> Key
    Input --> MouseButton

    package Event <<Frame>> {
      struct "*Event ..." as ConcreteEvent

      class EventDispatcher {
        {field} - handlers: map<type_index, vector<bool(const void*)>>
        + addHandler<T>(bool(const T&)): void
        + dispatch<T>(const T&): bool
      }
    }

    Application *-- EventDispatcher
  }
}

hide empty members

@enduml
